-- BetSim - esquema inicial (MVP: mercado 1X2)
-- Modelo generalizado mercado/opcion_cuota para soportar futuros mercados (ej. goleador) sin repintar.

CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(30)  NOT NULL UNIQUE,
    email          VARCHAR(120) NOT NULL UNIQUE,
    password_hash  VARCHAR(100) NOT NULL,
    saldo          NUMERIC(14,2) NOT NULL DEFAULT 50.00 CHECK (saldo >= 0),
    rol            VARCHAR(20)  NOT NULL DEFAULT 'USER',
    ultimo_bono    DATE,
    creado_en      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE liga (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(100) NOT NULL,
    sport_key VARCHAR(80)  NOT NULL UNIQUE,
    pais      VARCHAR(80),
    activa    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE partido (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    liga_id           BIGINT NOT NULL REFERENCES liga(id),
    external_id       VARCHAR(80) NOT NULL UNIQUE,
    equipo_local      VARCHAR(80) NOT NULL,
    equipo_visitante  VARCHAR(80) NOT NULL,
    inicio_utc        TIMESTAMP WITH TIME ZONE NOT NULL,
    fase              VARCHAR(20),
    estado            VARCHAR(20) NOT NULL DEFAULT 'PROGRAMADO',
    goles_local       INT,
    goles_visitante   INT
);
CREATE INDEX idx_partido_estado ON partido(estado);
CREATE INDEX idx_partido_inicio ON partido(inicio_utc);

CREATE TABLE mercado (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partido_id  BIGINT NOT NULL REFERENCES partido(id),
    tipo        VARCHAR(20) NOT NULL,
    estado      VARCHAR(20) NOT NULL DEFAULT 'ABIERTO',
    CONSTRAINT uq_mercado UNIQUE (partido_id, tipo)
);

CREATE TABLE opcion_cuota (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mercado_id    BIGINT NOT NULL REFERENCES mercado(id),
    codigo        VARCHAR(60) NOT NULL,
    descripcion   VARCHAR(120) NOT NULL,
    cuota         NUMERIC(6,2) NOT NULL,
    disponible    BOOLEAN NOT NULL DEFAULT TRUE,
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_opcion UNIQUE (mercado_id, codigo)
);

CREATE TABLE apuesta (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          BIGINT NOT NULL REFERENCES usuario(id),
    tipo                VARCHAR(20) NOT NULL,
    importe             NUMERIC(14,2) NOT NULL CHECK (importe > 0),
    cuota_total         NUMERIC(12,2) NOT NULL,
    retorno_potencial   NUMERIC(14,2) NOT NULL,
    estado              VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    creado_en           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resuelto_en         TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_apuesta_usuario ON apuesta(usuario_id);
CREATE INDEX idx_apuesta_estado ON apuesta(estado);

CREATE TABLE seleccion (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apuesta_id            BIGINT NOT NULL REFERENCES apuesta(id),
    opcion_cuota_id       BIGINT NOT NULL REFERENCES opcion_cuota(id),
    descripcion_snapshot  VARCHAR(160) NOT NULL,
    cuota_congelada       NUMERIC(6,2) NOT NULL,
    resultado             VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
);
CREATE INDEX idx_seleccion_apuesta ON seleccion(apuesta_id);
CREATE INDEX idx_seleccion_opcion ON seleccion(opcion_cuota_id);

CREATE TABLE transaccion (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id        BIGINT NOT NULL REFERENCES usuario(id),
    apuesta_id        BIGINT REFERENCES apuesta(id),
    tipo              VARCHAR(20) NOT NULL,
    importe           NUMERIC(14,2) NOT NULL,
    saldo_resultante  NUMERIC(14,2) NOT NULL,
    creado_en         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_transaccion_usuario ON transaccion(usuario_id);

-- Competición del MVP: Mundial 2026
INSERT INTO liga (nombre, sport_key, pais, activa)
VALUES ('Mundial 2026', 'soccer_fifa_world_cup', 'Internacional', TRUE);
